app/app/urls.py
from django.contrib import admin
from django.urls import (
    path,
    include
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todos/user/', include('user.urls')),
    path('', include('core.urls')),
    path('todos/task/', include('task.urls'))
]

app/core/urls.py
"""URL for home page."""
from django.urls import path
from core import views

name_app ='core'

urlpatterns = [
    path('', views.home_view, name='todo-home')
]

app/task/urls.py
from django.urls import path

from task import views

app_name = 'task'

urlpatterns = [
    path('tasks/<int:task_id>', views.task_detail, name='task-detail'),
    path('tasks/', views.task_list, name='tasks-list'),
    path('tasks/task_create', views.task_create, name='task-create'),
    path('tasks/task_update/<int:pk>', views.task_update, name='task-update'),
    path('tasks/delete/<int:pk>', views.task_delete, name='task-delete'),
]

app/user/urls.py
"""URL mapping for the user."""

from django.urls import path

from user import views

app_name = 'user'

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
]

app/core/models.py
"""
Models for app.
"""
from django.db import models
from django.contrib.auth.models import User

class Task(models.Model):
    """Model for tasks."""
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)


    def __str__(self):
        return self.title

app/task/forms.py
"""Form for tasks."""
from django import forms
from core.models import Task

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['id', 'title']
        read_only_fields = ['id']

class TaskDetailForm(TaskForm):
    class Meta(TaskForm.Meta):
        fields = TaskForm.Meta.fields + ['description']

app/core/views.py
"""Views for home page."""

from django.shortcuts import render

def home_view(request):
    return render(request, 'home.html')

app/task/views.py
"""Views for tasks."""
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden

from task.forms import TaskForm, TaskDetailForm
from core.models import Task

@login_required
def task_list(request):
    """Retrieve the list of tasks."""
    tasks = Task.objects.filter(user=request.user).order_by('-id')
    return render(request, 'task_list.html', {'tasks': tasks})

def task_detail(request, task_id):
    """Retrieve task with description."""
    task = get_object_or_404(Task, id=task_id)
    return render(request, 'task_detail.html', {'task': task})

@login_required
def task_create(request):
    if request.method == 'POST':
        form = TaskDetailForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.user = request.user
            task.save()
            messages.success(request, 'The task is created.')
            return redirect('task:task-detail', task_id=task.id)
    else:
        form = TaskDetailForm()
    return render(request, 'task_create.html', {'form': form})

def task_update(request, pk):
    """Create a new task."""
    task = get_object_or_404(Task, pk=pk)
    if request.method == 'POST':
        form = TaskDetailForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            messages.success(request, 'The task is changed.')
            return redirect('task:tasks-list')
        else:
            for field, errors in form.errors.items():
                for error in errors:
                    messages.error(request, f'Error: {error} in {field}')
                    return redirect('task:task-update', pk=pk)
    else:
        form = TaskDetailForm(instance=task)
    return render(request, 'task_update.html', {'form': form})
@login_required
def task_delete(request, pk):
    """Delete task."""
    task = get_object_or_404(Task, pk=pk)
    if task.user != request.user:
        return HttpResponseForbidden('You don`t have permition to delete this task.')
    if request.method == 'POST':
        task.delete()
        return redirect('task:tasks-list')
    return render(request, 'task_delete.html', {'task': task})

app/user/views.py
"""
Views for user.
"""
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import (
    UserCreationForm,
    AuthenticationForm,
)
from django.shortcuts import render, redirect

def register_view(request):
    """Generate form for user registration."""
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'User registered successfully. Please log in')
            return redirect('user:login')
        else:
            for field, errors in form.errors.items():
                for error in errors:
                    messages.error(request, f'Error in {field}: {error}')
            return redirect('user:register')
    else:
        form = UserCreationForm()
    return render(request, 'register.html', {'form': form})

def login_view(request):
    """Generate login for user."""
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('todo-home')
            else:
                return render(request, 'login.html', {'form': form, 'error message': 'invalid username or password'})
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})

def home_view(request):
    """Send authenticated user to home page."""
    if request.user.is_authenticated():
        return render(request, 'home.html')
    else:
        return redirect('login')

app/core/templates/home.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome to Your Todo List.</title>
</head>
<body>
    <header>
        <h1>Welcome to Your Todo List.</h1>
    </header>
    <nav>
        <ul>
            <li><a href="{% url 'todo-home' %}">Home</a></li>
            <li><a href="{% url 'user:register' %}">Register</a></li>
            <li><a href="{% url 'user:login' %}">Login</a></li>
            <li><a href="{% url 'task:tasks-list' %}">List Of Tasks</a></li>
            <li><a href="{% url 'task:task-create' %}">Create A New Task</a></li>
        </ul>
    </nav>
    <!--<main>
        <h2>Tasks</h2>
        <ul>
            {% for task in tasks%}
            <li>{{ task.title }}</li>
            {% endfor %}
        </ul>
    </main>-->
    <footer>
        <p>&copy; 2024 Your Todo List</p>
    </footer>
</body>
</html>

app/task/templates/task_create.html
<DOCTYPE! html>
<html lang='en'>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Task</title>
<body>
    <h1>Create Task</h1>
    <form method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button type = 'submit'>Create</button>
    </form>
</body>
</head>
</html>

app/task/templates/task_delete.html
<DOCTYPE! html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete Task</title>
<body>
    <h1>Delet Task</h1>
    <p>Are you sure you want to delete the task?</p>
    <p><strong>Title</strong>{{ task.title }}</p>
    <p><strong>Description</strong>{{ task.description }}</p>
    <form method='post'>
        {% csrf_token %}
        <button type='submit'>Delete</button>
    </form>
</body>
</head>
</html>

<!--<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete Task</title>
</head>
<body>
    <h1>Delete Task</h1>
    <p>Are you sure you want to delete the following task?</p>
    <p><strong>Title:</strong> {{ task.title }}</p>
    <p><strong>Description:</strong> {{ task.description }}</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Delete</button>
    </form>
</body>
</html>-->>

app/task/templates/task_detail.html
<DOCTYPE! html>
<html>
<head lang=en>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Task description.</title>
</head>
<body>
    <h1>Task Description</h1>
    <p><strong>Title: </strong>{{ task.title }}</p>
    <p><strong>Description: </strong>{{ task.description }}</p>
    <form action="{% url 'task:task-update' pk=task.id %}" method='get'>
        <button type=submit>Update</button>
    </form>
    <form action="{% url 'task:task-delete' pk=task.id %}" method='get'>
        <button type=submit>Delete</button>
    </form>

</body>
</html>

app/task/templates/task_list.html
<!DOCTYPE html>
<html>
<head lang=en>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Task List</title>
</head>
<body>
    <h1>Task List</h1>
    <ul>
        {% for task in tasks %}
        <nav>
            <ul>
                <li><a href="{% url 'task:task-detail' task.id %}">{{ task.title }}</a></li>
            </ul>
        </nav>
        {% empty %}
        <li>No tasks available.</li>
        {% endfor %}
    </ul>
</body>
</html>

app/task/templates/task_update.html
<DOCTYPE! html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update Task</title>
</head>
<body>
    <h1>Update Task</h1>
    <form method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button type='submit'>Update</button>
    </from>
</body>
</html>

app/user/templates/login.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name='viewport' content='width=device-width, initial-scale=1.0'>
        <title>Login</title>
    </head>
    <body>
        <h2>Login</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type='submit'>Login</button>
        </form>
    </body>
</html>

app/user/templates/register.html
"""Templates for user."""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Registration</title>
</head>
<body>
    <h2>User Registration</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Register</button>
    </form>
</body>
</html>